// Generated by site/website/scripts/sync-product-icons.cjs; edit data/product-family.json.
export const productFamily = {
  "category": "The platform for developer and agent trust",
  "products": [
    {
      "id": "cilock",
      "name": "CI/lock",
      "icon": "cilock",
      "job": "Capture the work.",
      "description": "Capture signed evidence from builds, tests, and scans on your compute or hosted infrastructure.",
      "href": "https://cilock.dev/",
      "cta": "Explore CI/lock"
    },
    {
      "id": "pushgate",
      "name": "Pushgate",
      "icon": "gate",
      "job": "Check the push.",
      "description": "Require evidence before a push enters your repository through the gate.",
      "href": "https://pushgate.dev/",
      "cta": "Explore Pushgate"
    },
    {
      "id": "platform",
      "name": "TestifySec Platform",
      "icon": "platform",
      "job": "Manage gates. Reuse the evidence.",
      "description": "Manage repository gates and connect technical test results to compliance controls.",
      "href": "https://testifysec.com/product",
      "cta": "Explore the platform"
    }
  ]
} as const;
