//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package policy

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AiAnswer) DeepCopyInto(out *AiAnswer) {
	*out = *in
	if in.YesNo != nil {
		in, out := &in.YesNo, &out.YesNo
		*out = new(float64)
		**out = **in
	}
	if in.Score != nil {
		in, out := &in.Score, &out.Score
		*out = new(float64)
		**out = **in
	}
	if in.Probabilities != nil {
		in, out := &in.Probabilities, &out.Probabilities
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Confidence != nil {
		in, out := &in.Confidence, &out.Confidence
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AiAnswer.
func (in *AiAnswer) DeepCopy() *AiAnswer {
	if in == nil {
		return nil
	}
	out := new(AiAnswer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AiChoice) DeepCopyInto(out *AiChoice) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Deny != nil {
		in, out := &in.Deny, &out.Deny
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MinConfidence != nil {
		in, out := &in.MinConfidence, &out.MinConfidence
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AiChoice.
func (in *AiChoice) DeepCopy() *AiChoice {
	if in == nil {
		return nil
	}
	out := new(AiChoice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AiDecision) DeepCopyInto(out *AiDecision) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(RegoPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.YesNo != nil {
		in, out := &in.YesNo, &out.YesNo
		*out = new(AiYesNo)
		(*in).DeepCopyInto(*out)
	}
	if in.Choice != nil {
		in, out := &in.Choice, &out.Choice
		*out = new(AiChoice)
		(*in).DeepCopyInto(*out)
	}
	if in.Score != nil {
		in, out := &in.Score, &out.Score
		*out = new(AiScore)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AiDecision.
func (in *AiDecision) DeepCopy() *AiDecision {
	if in == nil {
		return nil
	}
	out := new(AiDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AiPolicy) DeepCopyInto(out *AiPolicy) {
	*out = *in
	if in.Decision != nil {
		in, out := &in.Decision, &out.Decision
		*out = new(AiDecision)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AiPolicy.
func (in *AiPolicy) DeepCopy() *AiPolicy {
	if in == nil {
		return nil
	}
	out := new(AiPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AiScore) DeepCopyInto(out *AiScore) {
	*out = *in
	if in.Levels != nil {
		in, out := &in.Levels, &out.Levels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MinScore != nil {
		in, out := &in.MinScore, &out.MinScore
		*out = new(float64)
		**out = **in
	}
	if in.MaxScore != nil {
		in, out := &in.MaxScore, &out.MaxScore
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AiScore.
func (in *AiScore) DeepCopy() *AiScore {
	if in == nil {
		return nil
	}
	out := new(AiScore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AiYesNo) DeepCopyInto(out *AiYesNo) {
	*out = *in
	if in.Criteria != nil {
		in, out := &in.Criteria, &out.Criteria
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MinProbability != nil {
		in, out := &in.MinProbability, &out.MinProbability
		*out = new(float64)
		**out = **in
	}
	if in.MaxProbability != nil {
		in, out := &in.MaxProbability, &out.MaxProbability
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AiYesNo.
func (in *AiYesNo) DeepCopy() *AiYesNo {
	if in == nil {
		return nil
	}
	out := new(AiYesNo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Attestation) DeepCopyInto(out *Attestation) {
	*out = *in
	if in.RegoPolicies != nil {
		in, out := &in.RegoPolicies, &out.RegoPolicies
		*out = make([]RegoPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AiPolicies != nil {
		in, out := &in.AiPolicies, &out.AiPolicies
		*out = make([]AiPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Attestation.
func (in *Attestation) DeepCopy() *Attestation {
	if in == nil {
		return nil
	}
	out := new(Attestation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertConstraint) DeepCopyInto(out *CertConstraint) {
	*out = *in
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Emails != nil {
		in, out := &in.Emails, &out.Emails
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Organizations != nil {
		in, out := &in.Organizations, &out.Organizations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.URIs != nil {
		in, out := &in.URIs, &out.URIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Roots != nil {
		in, out := &in.Roots, &out.Roots
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Extensions = in.Extensions
	if in.RequiredPolicyOIDs != nil {
		in, out := &in.RequiredPolicyOIDs, &out.RequiredPolicyOIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertConstraint.
func (in *CertConstraint) DeepCopy() *CertConstraint {
	if in == nil {
		return nil
	}
	out := new(CertConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAttestation) DeepCopyInto(out *ExternalAttestation) {
	*out = *in
	if in.Functionaries != nil {
		in, out := &in.Functionaries, &out.Functionaries
		*out = make([]Functionary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RegoPolicies != nil {
		in, out := &in.RegoPolicies, &out.RegoPolicies
		*out = make([]RegoPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AiPolicies != nil {
		in, out := &in.AiPolicies, &out.AiPolicies
		*out = make([]AiPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAttestation.
func (in *ExternalAttestation) DeepCopy() *ExternalAttestation {
	if in == nil {
		return nil
	}
	out := new(ExternalAttestation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Functionary) DeepCopyInto(out *Functionary) {
	*out = *in
	in.CertConstraint.DeepCopyInto(&out.CertConstraint)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Functionary.
func (in *Functionary) DeepCopy() *Functionary {
	if in == nil {
		return nil
	}
	out := new(Functionary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policy) DeepCopyInto(out *Policy) {
	*out = *in
	in.Expires.DeepCopyInto(&out.Expires)
	if in.Roots != nil {
		in, out := &in.Roots, &out.Roots
		*out = make(map[string]Root, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.TimestampAuthorities != nil {
		in, out := &in.TimestampAuthorities, &out.TimestampAuthorities
		*out = make(map[string]Root, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PublicKeys != nil {
		in, out := &in.PublicKeys, &out.PublicKeys
		*out = make(map[string]PublicKey, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make(map[string]Step, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ExternalAttestations != nil {
		in, out := &in.ExternalAttestations, &out.ExternalAttestations
		*out = make(map[string]ExternalAttestation, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policy.
func (in *Policy) DeepCopy() *Policy {
	if in == nil {
		return nil
	}
	out := new(Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicKey) DeepCopyInto(out *PublicKey) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicKey.
func (in *PublicKey) DeepCopy() *PublicKey {
	if in == nil {
		return nil
	}
	out := new(PublicKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegoPolicy) DeepCopyInto(out *RegoPolicy) {
	*out = *in
	if in.Module != nil {
		in, out := &in.Module, &out.Module
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegoPolicy.
func (in *RegoPolicy) DeepCopy() *RegoPolicy {
	if in == nil {
		return nil
	}
	out := new(RegoPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Root) DeepCopyInto(out *Root) {
	*out = *in
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Intermediates != nil {
		in, out := &in.Intermediates, &out.Intermediates
		*out = make([][]byte, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]byte, len(*in))
				copy(*out, *in)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Root.
func (in *Root) DeepCopy() *Root {
	if in == nil {
		return nil
	}
	out := new(Root)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Step) DeepCopyInto(out *Step) {
	*out = *in
	if in.Functionaries != nil {
		in, out := &in.Functionaries, &out.Functionaries
		*out = make([]Functionary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Attestations != nil {
		in, out := &in.Attestations, &out.Attestations
		*out = make([]Attestation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ArtifactsFrom != nil {
		in, out := &in.ArtifactsFrom, &out.ArtifactsFrom
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AttestationsFrom != nil {
		in, out := &in.AttestationsFrom, &out.AttestationsFrom
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExternalFrom != nil {
		in, out := &in.ExternalFrom, &out.ExternalFrom
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedUntracked != nil {
		in, out := &in.AllowedUntracked, &out.AllowedUntracked
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TimestampConstraint != nil {
		in, out := &in.TimestampConstraint, &out.TimestampConstraint
		*out = new(TimestampConstraint)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Step.
func (in *Step) DeepCopy() *Step {
	if in == nil {
		return nil
	}
	out := new(Step)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimestampConstraint) DeepCopyInto(out *TimestampConstraint) {
	*out = *in
	if in.NotBefore != nil {
		in, out := &in.NotBefore, &out.NotBefore
		*out = (*in).DeepCopy()
	}
	if in.NotAfter != nil {
		in, out := &in.NotAfter, &out.NotAfter
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimestampConstraint.
func (in *TimestampConstraint) DeepCopy() *TimestampConstraint {
	if in == nil {
		return nil
	}
	out := new(TimestampConstraint)
	in.DeepCopyInto(out)
	return out
}
