// jade:ring local

package dsse

// formal:differential dsse-intoto TestFormalDSSEDifferential
//
// Binds the Lean model in formal/dsse-intoto to this package. The vectors in
// formal/dsse-intoto/vectors/dsse-intoto.json are generated by the model
// (DsseIntoto/Vectors.lean; `lake build` fails when they are stale). Each
// case is replayed here against the real code:
//
//   - pae:    preauthEncode must produce the model's bytes exactly.
//   - verify: Envelope.Verify, with real ECDSA P-256 keys, real X.509 leaves
//     under a trusted and an untrusted root, and FakeTimestamper TSAs, must
//     return the model's verdict and the model's count of distinct keys.
//   - decode: encoding/json into Envelope must accept exactly what the model
//     accepts. envelopeDecodeModel names which model the shipped code must
//     match: "asbuilt" while the code has the refuted behaviour, "required"
//     once the fix lands.
//
// The test skips when the vectors are not on disk (a module checked out
// without the repository) and FAILS instead when JADE_FORMAL_DIFFERENTIAL=1.

import (
	"bytes"
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/aflock-ai/rookery/attestation/cryptoutil"
	"github.com/aflock-ai/rookery/attestation/timestamp"
)

// The decode fix landed in #10057 (url-safe base64, required fields).
const envelopeDecodeModel = "required"

func formalVectorsPath() string {
	return filepath.Join("..", "..", "formal", "dsse-intoto", "vectors", "dsse-intoto.json")
}

type formalVectors struct {
	PAE []struct {
		TypeHex  string `json:"type_hex"`
		BodyLen  int    `json:"body_len"`
		BodyByte int    `json:"body_byte"`
		HeadHex  string `json:"head_hex"`
	} `json:"pae"`
	Verify []formalVerifyCase `json:"verify"`
	Decode []struct {
		HasPayload     bool   `json:"hasPayload"`
		HasPayloadType bool   `json:"hasPayloadType"`
		HasSignatures  bool   `json:"hasSignatures"`
		Payload        string `json:"payload"`
		Sigs           []struct {
			Has bool   `json:"has"`
			Enc string `json:"enc"`
		} `json:"sigs"`
		AsBuilt  bool `json:"asbuilt"`
		Required bool `json:"required"`
	} `json:"decode"`
	Alphabet []struct {
		Hex string `json:"hex"`
		Std string `json:"std"`
		URL string `json:"url"`
	} `json:"alphabet"`
}

type formalCert struct {
	Key    int  `json:"key"`
	Chains bool `json:"chains"`
	NB     int  `json:"nb"`
	NA     int  `json:"na"`
}

type formalVerifyCase struct {
	Threshold int   `json:"threshold"`
	Verifiers []int `json:"verifiers"`
	TSAs      []int `json:"tsas"`
	Fallback  bool  `json:"fallback"`
	Sigs      []struct {
		KeyID  int         `json:"keyid"`
		Signer int         `json:"signer"`
		Good   bool        `json:"good"`
		Cert   *formalCert `json:"cert"`
		TS     []int       `json:"ts"`
	} `json:"sigs"`
	AsBuilt string `json:"asbuilt"`
}

func loadFormalVectors(t *testing.T) formalVectors {
	t.Helper()
	raw, err := os.ReadFile(formalVectorsPath())
	if err != nil {
		if os.Getenv("JADE_FORMAL_DIFFERENTIAL") != "" {
			t.Fatalf("JADE_FORMAL_DIFFERENTIAL is set but the model's vectors are unreadable: %v", err)
		}
		t.Skipf("formal vectors not on disk (%v); the differential needs the repository checkout", err)
	}
	var v formalVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("decode %s: %v", formalVectorsPath(), err)
	}
	return v
}

func TestFormalDSSEDifferential(t *testing.T) {
	v := loadFormalVectors(t)
	if len(v.PAE) == 0 || len(v.Verify) == 0 || len(v.Decode) == 0 {
		t.Fatalf("vectors are missing a section: pae=%d verify=%d decode=%d", len(v.PAE), len(v.Verify), len(v.Decode))
	}
	t.Run("pae", func(t *testing.T) { formalPAE(t, v) })
	t.Run("verify", func(t *testing.T) { formalVerify(t, v.Verify) })
	t.Run("decode", func(t *testing.T) { formalDecode(t, v) })
	t.Run("alphabet", func(t *testing.T) { formalAlphabet(t, v) })
}

// formalAlphabet replays the model's either_reads_url_as_std: the standard
// and URL-safe spellings the model encodes for a byte string both decode, in
// decodeBase64Field, to exactly those bytes.
func formalAlphabet(t *testing.T, v formalVectors) {
	if len(v.Alphabet) == 0 {
		t.Fatal("vectors are missing the alphabet section")
	}
	for i, c := range v.Alphabet {
		want, err := hex.DecodeString(c.Hex)
		if err != nil {
			t.Fatalf("alphabet case %d: bad hex %q: %v", i, c.Hex, err)
		}
		for _, spelling := range []string{c.Std, c.URL} {
			raw, err := json.Marshal(spelling)
			if err != nil {
				t.Fatalf("alphabet case %d: %v", i, err)
			}
			got, err := decodeBase64Field(raw)
			if err != nil || !bytes.Equal(got, want) {
				t.Errorf("alphabet case %d: %q decoded to %x (%v), model bytes %s", i, spelling, got, err, c.Hex)
			}
		}
	}
	t.Logf("alphabet: %d byte strings decode identically from both spellings", len(v.Alphabet))
}

func formalPAE(t *testing.T, v formalVectors) {
	bad := 0
	for i, c := range v.PAE {
		ty, err := hex.DecodeString(c.TypeHex)
		if err != nil {
			t.Fatalf("case %d: type_hex: %v", i, err)
		}
		head, err := hex.DecodeString(c.HeadHex)
		if err != nil {
			t.Fatalf("case %d: head_hex: %v", i, err)
		}
		body := bytes.Repeat([]byte{byte(c.BodyByte)}, c.BodyLen)
		want := append(append([]byte{}, head...), body...)
		if got := preauthEncode(string(ty), body); !bytes.Equal(got, want) {
			bad++
			if bad <= 10 {
				n := len(got)
				if n > 64 {
					n = 64
				}
				t.Errorf("pae case %d (type %q, body %d x %#x): got head %q, model %q", i, ty, c.BodyLen, c.BodyByte, got[:n], head)
			}
		}
	}
	if bad > 0 {
		t.Fatalf("pae: %d of %d cases disagree with the model", bad, len(v.PAE))
	}
	t.Logf("pae: %d cases agree with the model", len(v.PAE))
}

// formalWorld is the fixed key and PKI material a verify case is built from.
type formalWorld struct {
	keys      map[int]*ecdsa.PrivateKey
	trusted   *x509.Certificate
	trustedK  *ecdsa.PrivateKey
	untrusted *x509.Certificate
	untrustK  *ecdsa.PrivateKey
	base      time.Time
	serial    int64
}

func newFormalWorld(t *testing.T) *formalWorld {
	t.Helper()
	w := &formalWorld{keys: map[int]*ecdsa.PrivateKey{}, base: time.Now().UTC().Truncate(time.Second)}
	for k := 1; k <= 4; k++ {
		priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
		if err != nil {
			t.Fatal(err)
		}
		w.keys[k] = priv
	}
	w.trusted, w.trustedK = formalRoot(t, "formal trusted root", 1)
	w.untrusted, w.untrustK = formalRoot(t, "formal untrusted root", 2)
	w.serial = 100
	return w
}

func formalRoot(t *testing.T, cn string, serial int64) (*x509.Certificate, *ecdsa.PrivateKey) {
	t.Helper()
	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	tmpl := &x509.Certificate{
		SerialNumber:          big.NewInt(serial),
		Subject:               pkix.Name{CommonName: cn},
		NotBefore:             time.Now().AddDate(-50, 0, 0),
		NotAfter:              time.Now().AddDate(50, 0, 0),
		IsCA:                  true,
		BasicConstraintsValid: true,
		KeyUsage:              x509.KeyUsageCertSign,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &priv.PublicKey, priv)
	if err != nil {
		t.Fatal(err)
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		t.Fatal(err)
	}
	return cert, priv
}

// at maps a model time to a wall-clock time: model 1000 is "now".
func (w *formalWorld) at(m int) time.Time {
	return w.base.Add(time.Duration(m-1000) * time.Minute)
}

func (w *formalWorld) leaf(t *testing.T, c *formalCert) []byte {
	t.Helper()
	w.serial++
	issuer, issuerK := w.trusted, w.trustedK
	if !c.Chains {
		issuer, issuerK = w.untrusted, w.untrustK
	}
	tmpl := &x509.Certificate{
		SerialNumber: big.NewInt(w.serial),
		Subject:      pkix.Name{CommonName: fmt.Sprintf("formal leaf %d", c.Key)},
		NotBefore:    w.at(c.NB),
		NotAfter:     w.at(c.NA),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageCodeSigning},
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, issuer, &w.keys[c.Key].PublicKey, issuerK)
	if err != nil {
		t.Fatal(err)
	}
	return pem.EncodeToMemory(&pem.Block{Type: PemTypeCertificate, Bytes: der})
}

const (
	formalPayloadType = "application/vnd.test+json"
	formalPayload     = "hello"
)

func (w *formalWorld) envelope(t *testing.T, c formalVerifyCase) Envelope {
	t.Helper()
	env := Envelope{PayloadType: formalPayloadType, Payload: []byte(formalPayload), Signatures: []Signature{}}
	pae := preauthEncode(formalPayloadType, []byte(formalPayload))
	for _, s := range c.Sigs {
		msg := pae
		if !s.Good {
			msg = []byte{0}
		}
		sig, err := cryptoutil.NewECDSASigner(w.keys[s.Signer], crypto.SHA256).Sign(bytes.NewReader(msg))
		if err != nil {
			t.Fatal(err)
		}
		es := Signature{KeyID: fmt.Sprintf("keyid-%d", s.KeyID), Signature: sig}
		if s.Cert != nil {
			es.Certificate = w.leaf(t, s.Cert)
		}
		for _, ts := range s.TS {
			es.Timestamps = append(es.Timestamps, SignatureTimestamp{Type: TimestampRFC3161, Data: []byte(w.at(ts).Format(time.RFC3339))})
		}
		env.Signatures = append(env.Signatures, es)
	}
	return env
}

func (w *formalWorld) options(c formalVerifyCase) []VerificationOption {
	opts := []VerificationOption{VerifyWithThreshold(c.Threshold), VerifyWithRoots(w.trusted)}
	vs := make([]cryptoutil.Verifier, 0, len(c.Verifiers))
	for _, k := range c.Verifiers {
		vs = append(vs, cryptoutil.NewECDSAVerifier(&w.keys[k].PublicKey, crypto.SHA256))
	}
	if len(vs) > 0 {
		opts = append(opts, VerifyWithVerifiers(vs...))
	}
	if len(c.TSAs) > 0 {
		tvs := make([]timestamp.TimestampVerifier, 0, len(c.TSAs))
		for _, T := range c.TSAs {
			tvs = append(tvs, timestamp.FakeTimestamper{T: w.at(T)})
		}
		opts = append(opts, VerifyWithTimestampVerifiers(tvs...))
	}
	if c.Fallback {
		opts = append(opts, VerifyWithCurrentTimeFallback())
	}
	return opts
}

// formalKeyOf names the public key behind a verifier that passed.
func formalKeyOf(t *testing.T, v cryptoutil.Verifier) string {
	t.Helper()
	var pub crypto.PublicKey
	if xv, ok := v.(*cryptoutil.X509Verifier); ok {
		pub = xv.Certificate().PublicKey
	} else {
		raw, err := v.Bytes()
		if err != nil {
			t.Fatal(err)
		}
		if pub, err = cryptoutil.UnmarshalPEMToPublicKey(raw); err != nil {
			t.Fatal(err)
		}
	}
	id, err := cryptoutil.GeneratePublicKeyID(pub, crypto.SHA256)
	if err != nil {
		t.Fatal(err)
	}
	return id
}

func formalVerdict(t *testing.T, cvs []CheckedVerifier, err error) string {
	t.Helper()
	var inv ErrInvalidThreshold
	var nomatch ErrNoMatchingSigs
	var notmet ErrThresholdNotMet
	switch {
	case errors.As(err, &inv):
		return "invalidThreshold"
	case errors.As(err, &ErrNoSignatures{}):
		return "noSignatures"
	case errors.As(err, &nomatch):
		return "noMatching"
	case errors.As(err, &notmet):
		return fmt.Sprintf("thresholdNotMet:%d", notmet.Actual)
	case err != nil:
		return "error:" + err.Error()
	}
	keys := map[string]struct{}{}
	for _, cv := range cvs {
		if cv.Error == nil {
			keys[formalKeyOf(t, cv.Verifier)] = struct{}{}
		}
	}
	return fmt.Sprintf("ok:%d", len(keys))
}

func formalVerify(t *testing.T, cases []formalVerifyCase) {
	w := newFormalWorld(t)
	bad := 0
	for i, c := range cases {
		env := w.envelope(t, c)
		cvs, err := env.Verify(w.options(c)...)
		if got := formalVerdict(t, cvs, err); got != c.AsBuilt {
			bad++
			if bad <= 20 {
				js, _ := json.Marshal(c)
				t.Errorf("verify case %d: code %s, model %s\n  %s", i, got, c.AsBuilt, js)
			}
		}
	}
	if bad > 0 {
		t.Fatalf("verify: %d of %d cases disagree with the model", bad, len(cases))
	}
	t.Logf("verify: %d cases agree with the model", len(cases))
}

// formalB64 is a field value in the named alphabet class.
func formalB64(class string) string {
	switch class {
	case "both":
		return "aGVsbG8=" // "hello": no index-62/63 character
	case "std":
		return "+/8=" // 0xfb 0xff in the standard alphabet
	case "url":
		return "-_8=" // the same bytes in the URL-safe alphabet
	default:
		return "!!!!"
	}
}

func formalDecode(t *testing.T, v formalVectors) {
	bad := 0
	for i, c := range v.Decode {
		fields := []string{}
		if c.HasPayload {
			fields = append(fields, `"payload":"`+formalB64(c.Payload)+`"`)
		}
		if c.HasPayloadType {
			fields = append(fields, `"payloadType":"application/vnd.test+json"`)
		}
		if c.HasSignatures {
			sigs := []string{}
			for _, s := range c.Sigs {
				if s.Has {
					sigs = append(sigs, `{"keyid":"k","sig":"`+formalB64(s.Enc)+`"}`)
				} else {
					sigs = append(sigs, `{"keyid":"k"}`)
				}
			}
			fields = append(fields, `"signatures":[`+strings.Join(sigs, ",")+`]`)
		}
		doc := "{" + strings.Join(fields, ",") + "}"
		var env Envelope
		got := json.Unmarshal([]byte(doc), &env) == nil
		want := c.AsBuilt
		if envelopeDecodeModel == "required" {
			want = c.Required
		}
		if got != want {
			bad++
			if bad <= 20 {
				t.Errorf("decode case %d: code accepts=%v, %s model %v: %s", i, got, envelopeDecodeModel, want, doc)
			}
		}
	}
	if bad > 0 {
		t.Fatalf("decode: %d of %d cases disagree with the %s model", bad, len(v.Decode), envelopeDecodeModel)
	}
	t.Logf("decode: %d cases agree with the %s model", len(v.Decode), envelopeDecodeModel)
}
