#!/usr/bin/env python3
# Copyright 2026 The Rookery Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
r"""Regenerate the secretscan list of gitleaks' built-in path exceptions.

secretscan drops every path exception whose text is one that gitleaks ships
in its default config, because the pusher names every file. Operators vendor
the default config from whatever gitleaks release they had, or from the master
branch between releases (the raw master URL), so the list covers the default
config at every v8 tag and at every master commit that touched it, not only
the linked one. Master carried path texts that no tag has. gitleaks' README
also ships an example config whose allowlists operators paste. Its path texts
are unanchored ((.*?)(jpg|gif|doc) and go\.mod among them), so the list
covers every path text in the README's examples too. The gitleaks tree
also ships other configs: its own repo-root .gitleaks.toml (a useDefault
template named the way operators name theirs, whose testdata and .*test\.go
are unanchored) and the test and example configs under testdata/, test_data/
and examples/. The list covers every path text in every .toml file in the
tree as well.

Usage:
    plugins/attestors/secretscan/gen_gitleaks_path_patterns.py [GITLEAKS_CLONE]

With no argument it makes a blobless clone of github.com/gitleaks/gitleaks in
a temporary directory. It reads config/gitleaks.toml at every v8.* tag and at
every commit on origin/master that touched it (git log --full-history, so no
merge simplification hides a side-branch commit), and collects every string in
every "paths" array (global and per-rule allowlists, in both the [allowlist]
and [[allowlists]] forms). It does the same for README.md at every v8.* tag
and at every commit on origin/master that touched it: every toml fenced block,
parsed as TOML, plus every literal string in a "paths = [...]" array anywhere
else in the README (plain fences carry placeholder examples). Last it reads
every other .toml file in the tree at every v8.* tag and at every commit on
origin/master that touched a .toml file; a file that does not parse is
refused unless it has no "paths" key at all (gitleaks keeps deliberately
broken configs as fixtures, and one without the key has no text to miss).
It writes gitleaks_path_patterns.go, next to itself. The Go test
TestLinkedGitleaksDefaultPathsArePinned fails when a gitleaks bump adds a
path pattern this list lacks; rerun this script then.
"""

import pathlib
import re
import subprocess
import sys
import tempfile
import tomllib

REPO = "https://github.com/gitleaks/gitleaks.git"
OUT = pathlib.Path(__file__).resolve().parent / "gitleaks_path_patterns.go"

HEADER = """// Code generated by plugins/attestors/secretscan/gen_gitleaks_path_patterns.py. DO NOT EDIT.

// Copyright 2026 The Rookery Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package secretscan

// gitleaksReleasedPathPatterns is the text of every path exception in the
// default config (config/gitleaks.toml) of gitleaks, global and per rule, at
// every v8 release from {first} to {last} ({tags} tags) and at every one of the
// {commits} commits on master up to {head} that touched it, plus every path
// text in the example configs of README.md at those tags and at the
// {readme_commits} master commits that touched README.md, plus every path text
// in every other .toml file in the gitleaks tree (its own .gitleaks.toml and
// the test and example configs) at those tags and at the {toml_commits} master
// commits that touched a .toml file. An operator config copied from any of
// those releases, master snapshots, README examples or repository configs
// carries these verbatim. "since" names the first tag that carried a text, or
// the first master commit for a text no tag carries; "README" marks a text
// that only the README examples carry, and a file name one that only that
// .toml file carries.
var gitleaksReleasedPathPatterns = []string{{
{body}}}
"""


def git(clone, *args):
    return subprocess.run(["git", "-C", clone, *args], check=True, capture_output=True, text=True).stdout


def collect(node, out):
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "paths" and isinstance(value, list):
                out.update(v for v in value if isinstance(v, str))
            else:
                collect(value, out)
    elif isinstance(node, list):
        for item in node:
            collect(item, out)


def go_string(s):
    if "`" not in s:
        return "`" + s + "`"
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def paths_at(clone, rev):
    try:
        text = git(clone, "show", rev + ":config/gitleaks.toml")
    except subprocess.CalledProcessError:
        sys.exit(rev + " has no config/gitleaks.toml; refusing to skip it")
    try:
        doc = tomllib.loads(text)
    except tomllib.TOMLDecodeError as e:
        sys.exit("{}:config/gitleaks.toml does not parse ({}); refusing to skip it".format(rev, e))
    found = set()
    collect(doc, found)
    return found


README_TOML = re.compile(r"^```toml[ \t]*\n(.*?)^```", re.S | re.M)
README_PATHS = re.compile(r"\bpaths\s*=\s*\[(.*?)\]", re.S)
README_LITERAL = re.compile(r"'''(.*?)'''", re.S)


def readme_paths_at(clone, rev):
    try:
        text = git(clone, "show", rev + ":README.md")
    except subprocess.CalledProcessError:
        sys.exit(rev + " has no README.md; refusing to skip it")
    found = set()
    for i, block in enumerate(README_TOML.findall(text)):
        try:
            doc = tomllib.loads(block)
        except tomllib.TOMLDecodeError as e:
            sys.exit("{}:README.md toml block {} does not parse ({}); refusing to skip it".format(rev, i, e))
        collect(doc, found)
    # Plain fences carry examples too, in literal strings. Any extra text
    # this picks up fails closed: it only drops an exception.
    for arr in README_PATHS.findall(text):
        found.update(README_LITERAL.findall(arr))
    return found


_toml_blob_paths = {}


def tree_toml_paths_at(clone, rev):
    """Return {path text: file} for every .toml file at rev but the default config."""
    found = {}
    for entry in git(clone, "ls-tree", "-r", "-z", rev).split("\0"):
        if not entry:
            continue
        meta, name = entry.split("\t", 1)
        _, kind, blob = meta.split()
        if kind != "blob" or not name.endswith(".toml") or name == "config/gitleaks.toml":
            continue
        if blob not in _toml_blob_paths:
            text = git(clone, "cat-file", "blob", blob)
            try:
                doc = tomllib.loads(text)
            except tomllib.TOMLDecodeError as e:
                if re.search(r"\bpaths\b", text):
                    sys.exit("{}:{} does not parse ({}) and has a paths key; refusing to skip it".format(rev, name, e))
                doc = {}
            texts = set()
            collect(doc, texts)
            _toml_blob_paths[blob] = texts
        for p in _toml_blob_paths[blob]:
            found.setdefault(p, name)
    return found


def main():
    if len(sys.argv) > 1:
        clone = sys.argv[1]
    else:
        clone = tempfile.mkdtemp(prefix="gitleaks-")
        subprocess.run(["git", "clone", "-q", "--filter=blob:none", "--no-checkout", REPO, clone], check=True)
    tags = git(clone, "tag", "-l", "v8.*", "--sort=v:refname").split()
    if not tags:
        sys.exit("no v8 tags in " + clone)
    head = git(clone, "rev-parse", "--verify", "origin/master^{commit}").strip()
    # Oldest first. A commit that deleted the file has no blob to read.
    commits = [
        c for c in git(clone, "log", "--full-history", "--reverse", "--format=%H", head, "--", "config/gitleaks.toml").split()
        if git(clone, "ls-tree", c, "--", "config/gitleaks.toml").strip()
    ]
    if not commits:
        sys.exit("no master commit touched config/gitleaks.toml in " + clone)
    readme_commits = [
        c for c in git(clone, "log", "--full-history", "--reverse", "--format=%H", head, "--", "README.md").split()
        if git(clone, "ls-tree", c, "--", "README.md").strip()
    ]
    if not readme_commits:
        sys.exit("no master commit touched README.md in " + clone)
    toml_commits = git(clone, "log", "--full-history", "--reverse", "--format=%H", head, "--", "*.toml").split()
    if not toml_commits:
        sys.exit("no master commit touched a .toml file in " + clone)
    first_seen = {}
    for tag in tags:
        for p in paths_at(clone, tag):
            first_seen.setdefault(p, tag)
    for c in commits:
        for p in paths_at(clone, c):
            first_seen.setdefault(p, "master " + c[:10] + ", no tag")
    for tag in tags:
        for p in readme_paths_at(clone, tag):
            first_seen.setdefault(p, "README " + tag)
    for c in readme_commits:
        for p in readme_paths_at(clone, c):
            first_seen.setdefault(p, "README master " + c[:10] + ", no tag")
    toml_texts = 0
    for tag in tags:
        for p, name in tree_toml_paths_at(clone, tag).items():
            toml_texts += 1
            first_seen.setdefault(p, name + " " + tag)
    for c in toml_commits:
        for p, name in tree_toml_paths_at(clone, c).items():
            toml_texts += 1
            first_seen.setdefault(p, name + " master " + c[:10] + ", no v8 tag")
    if not toml_texts:
        sys.exit("no .toml file in " + clone + " yielded a path text; the sweep read nothing")
    body = "".join("\t{},  // since {}\n".format(go_string(p), first_seen[p]) for p in sorted(first_seen))
    OUT.write_text(HEADER.format(first=tags[0], last=tags[-1], tags=len(tags), commits=len(commits), head=head[:10],
                                 readme_commits=len(readme_commits), toml_commits=len(toml_commits), body=body))
    subprocess.run(["gofmt", "-w", str(OUT)], check=True)
    print("wrote {} patterns from {} tags, {} config, {} README and {} .toml master commits (to {}) to {}".format(
        len(first_seen), len(tags), len(commits), len(readme_commits), len(toml_commits), head[:10], OUT))


if __name__ == "__main__":
    main()
