// Code generated by plugins/attestors/secretscan/gen_gitleaks_path_patterns.py. DO NOT EDIT.

// Copyright 2026 The Rookery Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package secretscan

// gitleaksReleasedPathPatterns is the text of every path exception in the
// default config (config/gitleaks.toml) of gitleaks, global and per rule, at
// every v8 release from v8.0.0 to v8.30.1 (107 tags) and at every one of the
// 240 commits on master up to b58d3f102c that touched it, plus every path
// text in the example configs of README.md at those tags and at the
// 310 master commits that touched README.md, plus every path text
// in every other .toml file in the gitleaks tree (its own .gitleaks.toml and
// the test and example configs) at those tags and at the 359 master
// commits that touched a .toml file. An operator config copied from any of
// those releases, master snapshots, README examples or repository configs
// carries these verbatim. "since" names the first tag that carried a text, or
// the first master commit for a text no tag carries; "README" marks a text
// that only the README examples carry, and a file name one that only that
// .toml file carries.
var gitleaksReleasedPathPatterns = []string{
	`(.*)?ssh`, // since examples/leaky-repo.toml master fae366a404, no v8 tag
	`(.*?)(doc|docx|zip|xls|pdf|bin|socket|vsidx|v2|suo|wsuo|.dll|pdb|exe|gltf)$`, // since v8.20.1
	`(.*?)(jpg|gif|doc)`, // since README v8.5.1
	`(.*?)(jpg|gif|doc|docx|zip|xls|pdf|bin|svg|socket)$`,                                                    // since v8.8.9
	`(.*?)(jpg|gif|doc|docx|zip|xls|pdf|bin|svg|socket|vsidx|v2|suo|wsuo|.dll|pdb|exe)$`,                     // since v8.17.0
	`(.*?)(jpg|gif|doc|docx|zip|xls|pdf|bin|svg|socket|vsidx|v2|suo|wsuo|.dll|pdb|exe|gltf)$`,                // since v8.19.3
	`(.*?)(jpg|gif|doc|pdf|bin|svg|socket)$`,                                                                 // since v8.0.3
	`(?:^|/)(?:Pipfile|poetry)\.lock$`,                                                                       // since v8.23.3
	`(?:^|/)(?:angular|bootstrap|jquery(?:-?ui)?|plotly|swagger-?ui)[a-zA-Z0-9.-]*(?:\.min)?\.js(?:\.map)?$`, // since v8.23.3
	`(?:^|/)(?:deno\.lock|npm-shrinkwrap\.json|package-lock\.json|pnpm-lock\.yaml|yarn\.lock)$`,              // since v8.24.0
	`(?:^|/)(?:npm-shrinkwrap\.json|package-lock\.json|pnpm-lock\.yaml|yarn\.lock)$`,                         // since v8.23.3
	`(?:^|/)@octokit/auth-token/README\.md$`,                                                                 // since v8.23.3
	`(?:^|/)\.git$`,                                                                                          // since v8.27.0
	`(?:^|/)\.mvn/wrapper/MavenWrapperDownloader\.java$`,                                                     // since v8.23.3
	`(?:^|/)bower_components(?:/.*)?$`,                                                                       // since v8.23.3
	`(?:^|/)gradle\.lockfile$`,                                                                               // since v8.23.3
	`(?:^|/)gradlew(?:\.bat)?$`,                                                                              // since v8.23.3
	`(?:^|/)javascript\.json$`,                                                                               // since v8.23.3
	`(?:^|/)mvnw(?:\.cmd)?$`,                                                                                 // since v8.23.3
	`(?:^|/)node_modules(?:/.*)?$`,                                                                           // since v8.23.3
	`(?:^|/)vendor/(?:bundle|ruby)(?:/.*?)?$`,                                                                // since v8.23.3
	`(?:^|/)vendor/(?:github\.com|golang\.org/x|google\.golang\.org|gopkg\.in|istio\.io|k8s\.io|sigs\.k8s\.io)(?:/.*)?$`, // since v8.23.3
	`(?:^|/)vendor/modules\.txt$`, // since v8.23.3
	`(?i)(?:^|/)(?:lib(?:64)?/python[23](?:\.\d{1,2})+|python/[23](?:\.\d{1,2})+/lib(?:64)?)(?:/.*)?$`, // since v8.23.3
	`(?i)(?:^|/)(?:v?env|virtualenv)/lib(?:64)?(?:/.*)?$`,                                              // since v8.23.3
	`(?i)(?:^|/)[a-z0-9_.]+-[0-9.]+\.dist-info(?:/.+)?$`,                                               // since v8.23.3
	`(?i)(^|/)(lib(64)?/python[23](\.\d{1,2})+/|python/[23](\.\d{1,2})+/lib(64)?/).+$`,                 // since v8.21.2
	`(?i)(^|/)(lib(64)?/python[23](\.\d{1,2})+|python/[23](\.\d{1,2})+/lib(64)?)(/.*)?$`,               // since v8.21.3
	`(?i)(^|/)[a-z0-9_.]+-[0-9.]+\.dist-info(/.+)?$`,                                                   // since v8.21.3
	`(?i)(^|/)[a-z0-9_.]+-[0-9.]+\.dist-info/.+$`,                                                      // since v8.20.1
	`(?i)/?(v?env|virtualenv)/lib(64)?(/.*)?$`,                                                         // since v8.21.3
	`(?i)/?(v?env|virtualenv)/lib(64)?/.+$`,                                                            // since v8.21.2
	`(?i)/?(v?env|virtualenv)/lib/.+$`,                                                                 // since v8.20.1
	`(?i)/?python/[23](\.\d{1,2})+/lib/.+$`,                                                            // since v8.20.1
	`(?i)/?python/lib/python[23](\.\d{1,2})+/.+$`,                                                      // since v8.20.1
	`(?i)\.(?:bmp|gif|jpe?g|png|svg|tiff?)$`,                                                           // since v8.23.3
	`(?i)\.(?:docx?|xlsx?|pdf|bin|socket|vsidx|v2|suo|wsuo|.dll|pdb|exe|gltf)$`,                        // since v8.27.0
	`(?i)\.(?:docx?|xlsx?|pdf|bin|socket|vsidx|v2|suo|wsuo|.dll|pdb|exe|gltf|zip)$`,                    // since v8.23.3
	`(?i)\.(?:eot|[ot]tf|woff2?)$`,                                                                     // since v8.23.3
	`(?i)\.(bmp|gif|jpe?g|svg|tiff?)$`,                                                                 // since v8.20.1
	`(^|/)(Pipfile|poetry)\.lock$`,                                                                     // since v8.21.2
	`(^|/)(angular|bootstrap|jquery(-?ui)?|plotly|swagger-?ui)[a-zA-Z0-9.-]*(\.min)?\.js(\.map)?$`,     // since v8.23.2
	`(^|/)(angular|jquery(-?ui)?|plotly|swagger-?ui)[a-zA-Z0-9.-]*(\.min)?\.js(\.map)?$`,               // since v8.21.3
	`(^|/)(angular|jquery(-?ui)?|plotly|swagger-?ui)[a-zA-Z0-9.-]+(\.min)?\.js(\.map)?$`,               // since master 5c2e8132f2, no tag
	`(^|/)(jquery(-?ui)?|swagger-?ui)-[a-zA-Z0-9.-]+\.js(\.map)?$`,                                     // since master 2db25f1367, no tag
	`(^|/)(jquery(-?ui)?|swagger-?ui)[a-zA-Z0-9.-]+\.js(\.map)?$`,                                      // since v8.21.2
	`(^|/)(npm-shrinkwrap\.json|package-lock\.json|pnpm-lock\.yaml|yarn\.lock)$`,                       // since v8.21.3
	`(^|/)@octokit/auth-token/README\.md$`,                                                             // since v8.21.2
	`(^|/)Pipfile\.lock$`,                                                                              // since v8.20.1
	`(^|/)\.mvn/wrapper/MavenWrapperDownloader\.java$`,                                                 // since v8.20.1
	`(^|/)bower_components(/.*)?$`,                                                                     // since v8.21.3
	`(^|/)bower_components/.*?$`,                                                                       // since v8.20.1
	`(^|/)cmd/generate/config/rules`,                                                                   // since .gitleaks.toml v8.21.2
	`(^|/)gradle\.lockfile$`,                                                                           // since v8.20.1
	`(^|/)gradlew(\.bat)?$`,                                                                            // since v8.20.1
	`(^|/)javascript\.json$`,                                                                           // since v8.23.2
	`(^|/)jquery(-ui)?-[a-zA-Z0-9.-]+\.js$`,                                                            // since master 50c2818167, no tag
	`(^|/)mvnw(\.cmd)?$`,                                                                               // since v8.20.1
	`(^|/)node_modules(/.*)?$`,                                                                         // since v8.21.3
	`(^|/)node_modules/.*?$`,                                                                           // since v8.20.1
	`(^|/)npm-shrinkwrap\.json$`,                                                                       // since v8.20.1
	`(^|/)package-lock\.json$`,                                                                         // since v8.20.1
	`(^|/)pnpm-lock\.yaml$`,                                                                            // since v8.20.1
	`(^|/)poetry\.lock$`,                                                                               // since v8.20.1
	`(^|/)vendor/(bundle|ruby)(/.*?)?$`,                                                                // since v8.21.3
	`(^|/)vendor/(bundle|ruby)/.*?$`,                                                                   // since v8.20.1
	`(^|/)vendor/(github\.com|golang\.org/x|google\.golang\.org|gopkg\.in|istio\.io|k8s\.io|sigs\.k8s\.io)(/.*)?$`, // since v8.21.3
	`(^|/)vendor/(github\.com|golang\.org/x|google\.golang\.org|gopkg\.in|istio\.io|k8s\.io|sigs\.k8s\.io)/.*$`,    // since v8.20.1
	`(^|/)vendor/modules\.txt$`,            // since v8.20.1
	`(^|/)yarn\.lock$`,                     // since v8.20.1
	`(go.mod|go.sum)$`,                     // since v8.4.0
	`(go.mod|go.sum|go.work|go.work.sum)$`, // since v8.19.0
	`.*test\.go`,                           // since .gitleaks.toml v8.28.0
	`.docx`,                                // since test_data/test_configs/allowlist_docx.toml master 86cfe0848b, no v8 tag
	`.git`,                                 // since test_data/test_repos/test_repo_10/.gitleaks.toml master 86cfe0848b, no v8 tag
	`.go`,                                  // since testdata/config/allow_path.toml v8.0.0
	`.py`,                                  // since test_data/test_configs/allowlist_global_files.toml master 2d58f1f94e, no v8 tag
	`.zip`,                                 // since test_data/test_configs/allowlist_files.toml master 86cfe0848b, no v8 tag
	`Database.refactorlog`,                 // since v8.14.0
	`\.(eot|[ot]tf|woff2?)$`,               // since v8.21.0
	`\.bb$`,                                // since v8.24.1
	`\.bbappend$`,                          // since v8.24.1
	`\.bbclass$`,                           // since v8.24.1
	`\.env\.prod$`,                         // since testdata/config/archives.toml v8.27.0
	`\.gem$`,                               // since v8.20.1
	`\.inc$`,                               // since v8.24.1
	`^.*\.(xml|log|json)$`,                 // since testdata/config/invalid/extend_invalid_ruleid.toml v8.29.0
	`^gitleaks\.toml$`,                     // since v8.20.1
	`^node_modules/.*`,                     // since testdata/config/valid/allowlist_global_multiple.toml v8.25.0
	`^path/to/your/problematic/file\.js$`,  // since testdata/config/valid/allowlist_rule_extend_default.toml v8.25.1
	`config(uration)?`,                     // since test_data/test_configs/aws_key_global_whitelist_path.toml master c4b07f5113, no v8 tag
	`gitleaks.toml`,                        // since v8.1.1
	`gitleaks\.toml`,                       // since v8.21.0
	`go\.(?:mod|sum|work(?:\.sum)?)$`,      // since v8.23.3
	`go\.(mod|sum|work(\.sum)?)$`,          // since v8.20.1
	`go\.mod`,                              // since README v8.5.1
	`go\.sum`,                              // since README v8.5.1
	`gradle.lockfile`,                      // since v8.16.1
	`ignore\.xaml`,                         // since testdata/config/extend_rule_allowlist.toml v8.19.3
	`node_modules`,                         // since v8.8.9
	`one-file-path-regex`,                  // since README v8.0.0
	`package-lock.json`,                    // since v8.15.4
	`package-lock\.json`,                   // since README v8.21.0
	`path-regex-a`,                         // since README master 656ef1c9a7, no tag
	`path-regex-b`,                         // since README master 656ef1c9a7, no tag
	`pnpm-lock.yaml`,                       // since v8.16.1
	`poetry.lock`,                          // since v8.19.0
	`something.py`,                         // since testdata/config/extend_empty_regexpath.toml v8.19.3
	`testdata`,                             // since .gitleaks.toml v8.28.0
	`tests/.+$`,                            // since v8.21.0
	`tests/expected/._\.json$`,             // since README v8.25.0
	`vendor`,                               // since v8.8.9
	`verification-metadata.xml`,            // since v8.19.0
	`verification-metadata\.xml`,           // since v8.21.3
	`yarn.lock`,                            // since v8.18.1
}
