// jade:ring local

// Code generated by formal/pushgate-ux (PushgateUx/FirstRunVectors.lean); DO NOT EDIT.
// Model: after.

package auth

// firstRunNeedles pairs a lower-cased phrase with the screen it guides to.
var firstRunNeedles = [][2]string{
	{"pushgate.dev", "pgHome"},
	{"cilock run", "attested"},
	{"return to your terminal", "terminal"},
}

// firstRunGuides is what the model says the callback surface guides to.
var firstRunGuides = []string{"terminal", "pgHome", "attested"}
