#!/usr/bin/env bash
# Re-record this fixture from a REAL vexctl run under cilock. The fixture is the
# recorded output of a real run — NOT a hand-authored sample — so re-record when
# vexctl changes and commit the diff (version/hash in fixture.yaml is the
# staleness signal). Requires: vexctl on PATH, and a cilock built with the vex
# attestor (e.g. `go build ./presets/all/cmd/cilock-all`).
#   CILOCK=/path/to/cilock-all ./record.sh
#
# Notes:
# - The vex attestor is POSTPRODUCT: it reads the OpenVEX product file from the
#   working dir (the file the wrapped command produced), re-digests it against
#   the product entry, and unmarshals it verbatim into the predicate
#   (vexDocument) plus the report file path and its digest.
# - The wrapped command is a real `vexctl create …` (a genuine vexctl
#   invocation) so the recorded evidence carries a real tool run. The product is
#   written with a RELATIVE filename (iam.openvex.json) in the working dir so the
#   attestor's reportFileName is relative, never an absolute home path.
# - The product/vuln are example IDENTIFIERS (a purl + a CVE) — they are the
#   SUBJECT of the VEX statement, not secrets.
# - SOURCE_DATE_EPOCH pins vexctl's document/statement timestamps so the run is
#   reproducible; the timestamps are still redacted in the contract (they are
#   carried through from the input, not generated by the attestor).
# - --attestations vex is MINIMAL on purpose: it omits the environment attestor
#   (which would dump host/env into the public attestation) and the git attestor
#   (the work dir is not a repo). cilock still adds command-run + product/material.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
CILOCK="${CILOCK:-cilock}"
WORK="$HERE/.record-work"; rm -rf "$WORK"; mkdir -p "$WORK"; trap 'rm -rf "$WORK"' EXIT
cp -R "$HERE/recording-input/." "$WORK/" 2>/dev/null || true
( cd "$WORK"
  openssl genpkey -algorithm ed25519 -out key.pem 2>/dev/null
  SOURCE_DATE_EPOCH=1700000000 "$CILOCK" run --step vex-scan --workload manual \
    --signer-file-key-path key.pem --outfile attestation.json \
    --attestations vex --enable-archivista=false \
    -- vexctl create \
         --product "pkg:oci/judge-api@sha256:6b5a8e9c1f3d2a4b7c8e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c" \
         --vuln "CVE-2024-3094" \
         --status "not_affected" \
         --justification "vulnerable_code_not_present" \
         --author "TestifySec Security" \
         --file iam.openvex.json )
cp "$WORK/iam.openvex.json" "$HERE/iam.openvex.json"
cp "$WORK/attestation.json" "$HERE/attestation.json"
echo "re-recorded. Update fixture.yaml recording: provenance to:"
echo "  version:       \"$(vexctl version 2>/dev/null | awk -F': +' '/GitVersion/{print $2; exit}')\""
echo "  binary_sha256: \"$(shasum -a 256 "$(command -v vexctl)" | awk '{print $1}')\""
